# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
install:
  - npm install
  - npm install htmllint-cli
sudo: false
node_js:
  - "8.12"
  - "10.0"
branches:
  only:
  - master

script:
  - ls -l
  - htmllint init
  - htmllint index.html
